# -*- coding: utf-8 -*-
"""BI3RP3_Simulation_FINAL_v.9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zXU089UoQa_jOozgbZzg5-il-3bdzlil
"""

# CELL 1: INSTALL + IMPORT LIBRARIES

!pip install --quiet numpy matplotlib scipy pandas statsmodels
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
from scipy.stats import entropy, f_oneway, ttest_ind, kruskal
from statsmodels.stats.multitest import multipletests
from tqdm.notebook import tqdm
from google.colab import files
import matplotlib.colors as mcolors
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# CELL 2: PARAMETERS (FINAL MODEL SETTINGS)

GRID = 20
N_STEPS = 500
N_TRIALS = 100
ENERGY_START = 100
STEP_COST = 1
E_SOURCE = 20
E_SINK = -30
P_SOURCE = 0.08
P_SINK = 0.04
RELOCATION_P = 0.01
HORIZON = 5
MC_SAMPLES = 50
AGENTS = ["random", "greedy", "cef"]
# Main seed used for primary reported figures/results
MAIN_SEED = 1000
# Extra seeds used to show robustness across runs
SEEDS = [1, 500, 1000, 1500, 2000]
# Actions: stay, right, left, down, up
MOVES = [(0, 0), (1, 0), (-1, 0), (0, 1), (0, -1)]

# CELL 3: RANDOM SEED FUNCTION

def set_seed(seed):
    """
    Set NumPy and Python random seeds for reproducibility.
    """
    np.random.seed(seed)
    random.seed(seed)

# CELL 4: ENVIRONMENT + MOVEMENT

def init_grid():
    """
    Create a sparse 20x20 environment:
    - 8% energy sources
    - 4% traps
    - 88% neutral cells
    """
    grid = np.zeros((GRID, GRID), dtype=int)
    probs = np.random.rand(GRID, GRID)
    grid[probs < P_SOURCE] = E_SOURCE
    grid[(probs >= P_SOURCE) & (probs < P_SOURCE + P_SINK)] = E_SINK
    return grid

# CELL 5: FUTURE-OPTIONS PROXY (CEF CORE IDEA)

def future_entropy_proxy(start_pos):
    """
    Approximate future optionality by simulating many short random
    rollouts from a candidate next position and counting the fraction
    of unique end positions reached.
    """
    reached = []
    for _ in range(MC_SAMPLES):
        pos = start_pos
        for _ in range(HORIZON):
            a = np.random.randint(len(MOVES))
            pos = move_pos(pos, a)
        reached.append(pos)
    return len(set(reached)) / MC_SAMPLES

# CELL 6: AGENT BEHAVIOURS

def random_move(grid, pos, energy):
    """
    Random agent: chooses any action uniformly at random.
    """
    return np.random.randint(len(MOVES))

def greedy_move(grid, pos, energy):
    """
    Greedy agent: chooses the move with the highest immediate cell value.
    A tiny penalty on staying still encourages movement.
    """
    best = 0
    best_val = -1e9
    for i in range(len(MOVES)):
        nx, ny = move_pos(pos, i)
        val = grid[nx, ny]
        if i == 0:
            val -= 0.1
        if val > best_val:
            best_val = val
            best = i
    return best

# CELL 7: SINGLE TRIAL SIMULATION

def run_trial(agent):
    """
    Run one complete trial for one agent.
    Returns:
    - steps: survival time
    - energy_trace: energy over time
    - final_energy: energy at the end of the trial
    """
    env = init_grid()
    pos = (GRID // 2, GRID // 2)
    energy = ENERGY_START
    energy_trace = []
    for t in range(N_STEPS):
        if energy <= 0:
            break
        if agent == "random":
            a = random_move(env, pos, energy)
        elif agent == "greedy":
            a = greedy_move(env, pos, energy)
        elif agent == "cef":
            a = cef_move(env, pos, energy)
        else:
            raise ValueError("Unknown agent type")
        new_pos = move_pos(pos, a)
        cell = env[new_pos]
        energy = energy + cell - STEP_COST
        # Consume energy source once visited
        if cell == E_SOURCE:
            env[new_pos] = 0
        energy_trace.append(max(energy, 0))
        pos = new_pos
        # Occasionally re-randomise environment
        if np.random.rand() < RELOCATION_P:
            env = init_grid()
    return {
        "steps": len(energy_trace),
        "energy_trace": np.array(energy_trace),
        "final_energy": energy
    }

# CELL 8: RUN FULL EXPERIMENT FOR ONE SEED

def run_experiment(seed):
    """
    Run all trials for all agent types under one chosen random seed.
    """
    set_seed(seed)
    results = {a: [] for a in AGENTS}
    for a in AGENTS:
        print("Running:", a)
        for _ in tqdm(range(N_TRIALS)):
            results[a].append(run_trial(a))
    return results

# CELL 9: EXTRACT METRICS

def extract_steps(results):
    """
    Extract survival times for each agent.
    """
    return {a: [r["steps"] for r in results[a]] for a in AGENTS}

def extract_final_energy(results):
    """
    Extract final energies for each agent.
    """
    return {a: [r["final_energy"] for r in results[a]] for a in AGENTS}

# CELL 10: STATISTICS

def run_stats(results):
    """
    Run:
    - one-way ANOVA
    - Kruskal-Wallis
    - pairwise Welch t-tests
    - Bonferroni correction
    """
    steps = extract_steps(results)
    r = steps["random"]
    g = steps["greedy"]
    c = steps["cef"]
    # One-way ANOVA
    F, p_anova = f_oneway(r, g, c)
    # Non-parametric check
    H, p_kw = kruskal(r, g, c)
    # Pairwise Welch t-tests
    tests = [
        ttest_ind(r, g, equal_var=False),
        ttest_ind(r, c, equal_var=False),
        ttest_ind(g, c, equal_var=False)
    ]
    pvals = [t.pvalue for t in tests]
    corrected = multipletests(pvals, method="bonferroni")
    return F, p_anova, H, p_kw, tests, corrected

# CELL 11: NEGENTROPY CALCULATION

def compute_negentropy(results, bins=12):
    """
    At each time step, compute Shannon entropy across trial energy values
    and convert it to negentropy
    """
    neg = {}
    for agent in AGENTS:
        max_len = max(len(r["energy_trace"]) for r in results[agent])
        arr = np.full((len(results[agent]), max_len), np.nan)
        for i, r in enumerate(results[agent]):
            arr[i, :len(r["energy_trace"])] = r["energy_trace"]
        neg_series = []
        for t in range(arr.shape[1]):
            vals = arr[:, t]
            vals = vals[~np.isnan(vals)]
            if len(vals) == 0:
                neg_series.append(np.nan)
                continue
            hist, _ = np.histogram(vals, bins=bins, range=(0, ENERGY_START))
            if np.sum(hist) == 0:
                neg_series.append(np.nan)
                continue
            p = hist / np.sum(hist)
            p = p + 1e-12  # avoid log(0)
            S = entropy(p, base=np.e)
            S_max = np.log(len(p))
            neg_series.append(S_max - S)
        neg[agent] = np.array(neg_series)
    return neg

# CELL 12: MAIN RUN (PRIMARY RESULTS)

results_main = run_experiment(MAIN_SEED)
steps_main = extract_steps(results_main)
final_main = extract_final_energy(results_main)
neg_main = compute_negentropy(results_main)
print("\n--- MEAN SURVIVAL ---")
for a in AGENTS:
    print(a, "mean =", np.mean(steps_main[a]), "std =", np.std(steps_main[a]))
print("\n--- MEAN FINAL ENERGY ---")
for a in AGENTS:
    print(a, "mean =", np.mean(final_main[a]), "std =", np.std(final_main[a]))
print("\n--- MEAN NEGENTROPY ---")
for a in AGENTS:
    print(a, "mean =", np.nanmean(neg_main[a]))

# CELL 13: STATISTICAL RESULTS

F, p_anova, H, p_kw, tests, corrected = run_stats(results_main)
print("\n--- ANOVA ---")
print("F =", F, "p =", p_anova)
print("\n--- KRUSKAL-WALLIS ---")
print("H =", H, "p =", p_kw)
labels = ["random vs greedy", "random vs cef", "greedy vs cef"]
print("\n--- PAIRWISE TESTS (BONFERRONI CORRECTED) ---")
for i, label in enumerate(labels):
    print(
        label,
        "| raw p =", tests[i].pvalue,
        "| corrected p =", corrected[1][i]
    )

# CELL 14: VISUAL 1 - SURVIVAL BAR CHART

means_steps = [np.mean(steps_main[a]) for a in AGENTS]
stds_steps = [np.std(steps_main[a]) for a in AGENTS]
plt.figure(figsize=(6, 4))
plt.bar(AGENTS, means_steps, yerr=stds_steps, capsize=5)
plt.ylabel("Survival time (steps)")
plt.title(f"Mean Survival Time by Agent Type (Seed = {MAIN_SEED})")
plt.grid(axis="y", alpha=0.3)
plt.show()

# CELL 15: VISUAL 2 - MEAN ENERGY VS TIME

plt.figure(figsize=(9, 6))
for agent in AGENTS:
    max_len = max(len(r["energy_trace"]) for r in results_main[agent])
    arr = np.full((len(results_main[agent]), max_len), np.nan)
    for i, r in enumerate(results_main[agent]):
        arr[i, :len(r["energy_trace"])] = r["energy_trace"]
    mean_energy = np.nanmean(arr, axis=0)
    std_energy = np.nanstd(arr, axis=0)
    t = np.arange(len(mean_energy))
    plt.plot(t, mean_energy, label=agent)
    plt.fill_between(
        t,
        mean_energy - std_energy,
        mean_energy + std_energy,
        alpha=0.15
    )
plt.xlabel("Time step")
plt.ylabel("Energy (mean ± SD)")
plt.title(f"Mean Energy vs Time by Agent Type (Seed = {MAIN_SEED})")
plt.legend()
plt.grid(True)
plt.show()

# CELL 16: VISUAL 3 - NEGENTROPY VS TIME

plt.figure(figsize=(9, 6))
for agent in AGENTS:
    plt.plot(neg_main[agent], label=agent)
plt.xlabel("Time step")
plt.ylabel("Negentropy (Smax - S)")
plt.title(f"Negentropy vs Time by Agent Type (Seed = {MAIN_SEED})")
plt.legend()
plt.grid(True)
plt.show()

# CELL 17: SAVE + DOWNLOAD MAIN SUMMARY TABLES

summary_main_df = pd.DataFrame({
    "agent": AGENTS,
    "mean_steps": [np.mean(steps_main[a]) for a in AGENTS],
    "std_steps": [np.std(steps_main[a]) for a in AGENTS],
    "mean_final_energy": [np.mean(final_main[a]) for a in AGENTS],
    "std_final_energy": [np.std(final_main[a]) for a in AGENTS],
    "mean_negentropy": [np.nanmean(neg_main[a]) for a in AGENTS]
})
pairwise_df = pd.DataFrame({
    "comparison": labels,
    "t_statistic": [tests[i].statistic for i in range(3)],
    "raw_p_value": [tests[i].pvalue for i in range(3)],
    "bonferroni_p_value": [corrected[1][i] for i in range(3)],
    "significant_after_correction": [corrected[0][i] for i in range(3)]
})
overall_stats_df = pd.DataFrame({
    "anova_F": [F],
    "anova_p": [p_anova],
    "kruskal_H": [H],
    "kruskal_p": [p_kw]
})
summary_main_df.to_csv("summary_main.csv", index=False)
pairwise_df.to_csv("pairwise_main.csv", index=False)
overall_stats_df.to_csv("overall_stats_main.csv", index=False)
print("\nSaved main files:")
print("- summary_main.csv")
print("- pairwise_main.csv")
print("- overall_stats_main.csv")
files.download("summary_main.csv")
files.download("pairwise_main.csv")
files.download("overall_stats_main.csv")

# CELL 18: MULTI-SEED ROBUSTNESS ANALYSIS

rows = []
stats_rows = []
for seed in SEEDS:
    print("\nRunning seed:", seed)
    res = run_experiment(seed)
    steps = extract_steps(res)
    finals = extract_final_energy(res)
    neg = compute_negentropy(res)
    F_seed, p_anova_seed, H_seed, p_kw_seed, _, _ = run_stats(res)
    for a in AGENTS:
        rows.append({
            "seed": seed,
            "agent": a,
            "mean_steps": np.mean(steps[a]),
            "std_steps": np.std(steps[a]),
            "mean_final_energy": np.mean(finals[a]),
            "std_final_energy": np.std(finals[a]),
            "mean_negentropy": np.nanmean(neg[a])
        })
    stats_rows.append({
        "seed": seed,
        "anova_F": F_seed,
        "anova_p": p_anova_seed,
        "kruskal_H": H_seed,
        "kruskal_p": p_kw_seed
    })
robust_df = pd.DataFrame(rows)
robust_stats_df = pd.DataFrame(stats_rows)

# CELL 19: ROBUSTNESS SUMMARY TABLE

robust_summary_df = (
    robust_df
    .groupby("agent")[["mean_steps", "mean_final_energy", "mean_negentropy"]]
    .agg(["mean", "std"])
)
print("\n--- ROBUSTNESS SUMMARY ACROSS SEEDS ---")
print(robust_summary_df)

# CELL 20: VISUAL 4 - ROBUSTNESS BAR CHART

robust_bar = robust_df.groupby("agent")["mean_steps"].agg(["mean", "std"]).reset_index()
plt.figure(figsize=(6, 4))
plt.bar(robust_bar["agent"], robust_bar["mean"], yerr=robust_bar["std"], capsize=5)
plt.ylabel("Mean survival across seeds")
plt.title("Robustness of Survival Across Random Seeds")
plt.grid(axis="y", alpha=0.3)
plt.show()

# CELL 21: VISUAL 5 - PER-SEED SURVIVAL LINE PLOT

plt.figure(figsize=(8, 5))
for agent in AGENTS:
    sub = robust_df[robust_df["agent"] == agent].sort_values("seed")
    plt.plot(sub["seed"], sub["mean_steps"], marker="o", label=agent)
plt.xlabel("Seed")
plt.ylabel("Mean survival time")
plt.title("Mean Survival by Seed and Agent Type")
plt.legend()
plt.grid(True)
plt.show()

# CELL 22: SAVE + DOWNLOAD ROBUSTNESS TABLES

robust_df.to_csv("robustness.csv", index=False)
robust_stats_df.to_csv("robustness_stats.csv", index=False)
print("\nSaved robustness files:")
print("- robustness.csv")
print("- robustness_stats.csv")
files.download("robustness.csv")
files.download("robustness_stats.csv")

# CELL 23: ANIMATION

def visualise_grid(env, agent_pos):
    """
    Convert simulation grid values into display codes:
    0 = neutral (white)
    1 = trap (red)
    2 = source (green)
    3 = agent (blue)
    """
    frame = np.zeros_like(env, dtype=int)
    frame[env == 0] = 0
    frame[env == E_SINK] = 1
    frame[env == E_SOURCE] = 2
    x, y = agent_pos
    frame[x, y] = 3
    return frame

def run_trial_with_frames(agent):
    """
    Run one full trial and store grid frames for animation.
    """
    env = init_grid()
    pos = (GRID // 2, GRID // 2)
    energy = ENERGY_START
    frames = []
    energy_trace = []
    for t in range(N_STEPS):
        if energy <= 0:
            break
        frames.append(visualise_grid(env, pos))
        if agent == "random":
            a = random_move(env, pos, energy)
        elif agent == "greedy":
            a = greedy_move(env, pos, energy)
        elif agent == "cef":
            a = cef_move(env, pos, energy)
        else:
            raise ValueError("Unknown agent type")
        new_pos = move_pos(pos, a)
        cell = env[new_pos]
        energy = energy + cell - STEP_COST
        if cell == E_SOURCE:
            env[new_pos] = 0
        energy_trace.append(max(energy, 0))
        pos = new_pos
        if np.random.rand() < RELOCATION_P:
            env = init_grid()
    return {
        "frames": frames,
        "energy_trace": np.array(energy_trace)
    }

def generate_visual_trials(seed=MAIN_SEED):
    """
    Generate one representative animated trial for each agent.
    """
    set_seed(seed)
    visual_results = {}
    for agent in AGENTS:
        visual_results[agent] = run_trial_with_frames(agent)
    return visual_results

def animate_visual_trials(visual_results, interval_ms=300):
    """
    Display one animated trial for each agent side by side.
    """
    cmap_env = mcolors.ListedColormap([
        "white",   # 0 neutral
        "red",     # 1 trap
        "green",   # 2 source
        "blue"     # 3 agent
    ])
    fig, axes = plt.subplots(
        1, 6, figsize=(18, 6),
        gridspec_kw={"width_ratios": [1, 0.6, 1, 0.6, 1, 0.6]}
    )
    plt.tight_layout()
    plt.close(fig)
    imgs = []
    bars = []
    max_frames = min(len(visual_results[a]["frames"]) for a in AGENTS)
    for i, agent in enumerate(AGENTS):
        ax_grid = axes[2 * i]
        ax_bar = axes[2 * i + 1]
        first_frame = visual_results[agent]["frames"][0]
        first_energy = visual_results[agent]["energy_trace"][0] if len(visual_results[agent]["energy_trace"]) > 0 else 0
        img = ax_grid.imshow(first_frame, cmap=cmap_env, vmin=0, vmax=3)
        ax_grid.set_title(agent.upper())
        ax_grid.set_xticks([])
        ax_grid.set_yticks([])
        bar = ax_bar.bar([0], [first_energy], color="blue")
        ax_bar.set_ylim(0, ENERGY_START)
        ax_bar.set_xticks([])
        ax_bar.set_title(f"Energy: {first_energy:.1f}")
        imgs.append(img)
        bars.append(bar)
    def update(frame_idx):
        artists = []
        for i, agent in enumerate(AGENTS):
            imgs[i].set_data(visual_results[agent]["frames"][frame_idx])
            if frame_idx < len(visual_results[agent]["energy_trace"]):
                energy_val = visual_results[agent]["energy_trace"][frame_idx]
            else:
                energy_val = 0
            bars[i][0].set_height(energy_val)
            axes[2 * i + 1].set_title(f"Energy: {energy_val:.1f}")
            artists.append(imgs[i])
            artists.append(bars[i][0])
        return artists
    anim = FuncAnimation(fig, update, frames=max_frames, interval=interval_ms, blit=False)
    return HTML(anim.to_jshtml())

# CELL 24: RUN ANIMATION

visual_results = generate_visual_trials(seed=MAIN_SEED)
animate_visual_trials(visual_results, interval_ms=300)